### ISSUE TITLE
Using jshell in java example

### ISSUE THREAD

**Issue by ThomasCarstens** [mavlink/MAVSDK-Java#100]
I tried to load jshell with mavsdk classes as per https://github.com/mavlink/MAVSDK-Java/tree/main/examples/java-client

I can't seem to use jshell within the java example project, even though jshell works with ```jshell``` on my installation.
Am I missing a vital step? Thanks!

Behaviour:
```
./gradlew jshell

FAILURE: Build failed with an exception.

* What went wrong:
Task 'jshell' not found in root project 'MAVSDK-Java-example'. Some candidates are: 'help'.
```

**Comment by ThomasCarstens** [comment]
Ah I see, thanks for the heads up.

**Comment by JonasVautherin** [comment]
Let me know if you find a good way to import a project in jshell. In the meantime I'll close this.
