### ISSUE TITLE
How to stop manual control?

### ISSUE THREAD

**Issue by xumeng367** [mavlink/MAVSDK-Java#101]
When i start manual contorl ,i call  drone.getManualControl().startPositionControl(), but no stop method,so when stop call drone.getManualControl().setManualControlInputI(), the drone will lost control and return go home?

**Comment by julianoes** [comment]
Yes, that's correct. If you no longer set the manual control input, it should detect it as a timeout and trigger the failsafe action configured for RC loss.

**Comment by xumeng367** [comment]
How do I hover the drone and then execute a mission?

**Comment by julianoes** [comment]
You send a takeoff using `action->takeoff()`, then you do `mission->start_mission()`. I would first try these things out in simulation and also using QGC to learn more about how it works.
