### ISSUE TITLE
android-client example not connecting to simulated drone and crashing when pressing Takeoff or Land button

### ISSUE THREAD

**Issue by iura1** [mavlink/MAVSDK-Java#126]
Hi all, Does anyone have experience running the MAVSDK-Java android-client example? I can run it on the emulator in Android Studio but it is not connecting to Jmavsim Simulator, and it is crashing when I press land or takeoff button. I am using mavsdk_server built from sources. Please check the attached screenshots. Thx!

![Screenshot from 2023-03-26 21-25-21](https://user-images.githubusercontent.com/15063130/227796324-dcd1e20f-87b2-4741-a99d-1c65eedbe1ec.png)
![Screenshot from 2023-03-26 21-25-29](https://user-images.githubusercontent.com/15063130/227796317-9a165c92-c991-485c-a765-2ab663244d44.png)

**Comment by JonasVautherin** [comment]
Please link the other posts when you post the same question on different places: https://discuss.px4.io/t/android-client-example-not-connecting-to-simulated-drone-and-crashing-when-pressing-takeoff-or-land-button/31383

What I answered there: 

> I think you have to check the networking there. Your emulator is (I believe) not on the host network (it has an IP like 10.0.2.2, something like that). So you’ll have to send mavlink from jmavsim to the emulated device somehow.

**Comment by julianoes** [comment]
Follow up over there, closing this.
