### ISSUE TITLE
Mission speed seems to be ignored

### ISSUE THREAD

**Issue by RyanHurst** [mavlink/MAVSDK-Java#13]
Missions seems to be run at the same speed regardless of what speedMS is passed in to the MissionItem.

**Comment by julianoes** [comment]
I think this is a recent PX4 Firmware bug presumably fixed now:
https://github.com/PX4/Firmware/issues/11764

**Comment by JonasVautherin** [comment]
@RyanHurst which version of the Firmware are you using? Could you confirm that?

**Comment by JonasVautherin** [comment]
@RyanHurst Did you have a chance to check the Firmware version?

**Comment by RyanHurst** [comment]
My firmware is built from commit e6f1a2db12def90cbe849ffe8898b5547b72e5f5 (april 2nd)

**Comment by julianoes** [comment]
You need something after April 15.
https://github.com/PX4/Firmware/pull/11849
https://github.com/PX4/Firmware/pull/11836

**Comment by julianoes** [comment]
Closing this, please re-open if its a problem again.
