### ISSUE TITLE
run() function can't get the heartbeat

### ISSUE THREAD

**Issue by Zxr1230** [mavlink/MAVSDK-Java#140]
I am using Mavsdk server with a UDP connection. I installed the android-client example on the Herelink controller. I tried using the default which is 14540 and I also tried 14550 and 14552, but none works. I wonder if there are any other things I should do? Thank you!
![image](https://github.com/mavlink/MAVSDK-Java/assets/47097582/ecc61287-635d-49ff-ac9d-4aed4eb2edd1)

**Comment by julianoes** [comment]
Looks like a duplicate of https://github.com/mavlink/MAVSDK-Java/issues/139.
