### ISSUE TITLE
Using MavLink-Java for FTP File upload prompts a timeout

### ISSUE THREAD

**Issue by QZH-Caesar** [mavlink/MAVSDK-Java#142]
The following is my code and logs for reference:

`String fileName = "file.text";
        File file = new File(getFilesDir(),fileName);
        try {
          FileOutputStream outputStream = new FileOutputStream(file);;
          String content = "Hello,World!";
          if (file.canRead() && file.canWrite()){
            byte[] bytes = content.getBytes();
            outputStream.write(bytes);
          }
          FileReader fileReader = new FileReader(file);
          BufferedReader bufferedReader = new BufferedReader(fileReader);
          String redStr = bufferedReader.readLine();
          logger.debug("File Message" + redStr);
        } catch (IOException e) {
          e.printStackTrace();
        }
        MavsdkEventQueue.executor().execute(() ->{
          disposables.add(
                  drone.getFtp().setTargetCompid(1)
                          .subscribe());});
        disposables.add(
                drone.getFtp().upload(file.getPath(),"/fs/microsd/").subscribe(
                        onNext -> {
                          logger.debug("FTP upload" + onNext.getTotalBytes());
                        },
                        throwable ->{
                          logger.debug("FTP error" + throwable.getMessage());
                        }
                )
        );`
`D/Mavsdk: MAVLink: info: System id: 1	
D/MapsActivity: [grpc-default-executor-0] - FTP upload12
W/Mavsdk: Response timeout. Retry: 1
W/Mavsdk: Response timeout. Retry: 1
W/Mavsdk: Response timeout. Retry: 1
W/Mavsdk: Response timeout. Retry: 1`

**Comment by julianoes** [comment]
FTP has been rewritten and will be part of MAVSDK v2.
