### ISSUE TITLE
Unable to get flight mode

### ISSUE THREAD

**Issue by Zxr1230** [mavlink/MAVSDK-Java#143]
I am trying to run the Mavsdk in the android-client example.  The Android example app is installed in the Herelink ground controller. After connecting the drone, the app displays the flight mode unknown but the flight mode displayed by the drone is LOIT. 
Thanks in advance! 
![image](https://github.com/mavlink/MAVSDK-Java/assets/47097582/ca2009b6-0dad-43d5-b7d0-059645c7b536)
![image](https://github.com/mavlink/MAVSDK-Java/assets/47097582/3a60715c-666c-4d95-854f-aa1d285dc828)

**Comment by JonasVautherin** [comment]
Somehow I feel like I have seen that picture already. Did you open another issue somewhere else?

**Comment by JonasVautherin** [comment]
Does the rest work? E.g. do you get correct battery updates?

**Comment by Zxr1230** [comment]
> Does the rest work? E.g. do you get correct battery updates?

Thanks! I think it works. But when I press the take-off button, the app will crash. 
![image](https://github.com/mavlink/MAVSDK-Java/assets/47097582/b3c032ae-14ec-4b86-9336-a355ee042598)

**Comment by JonasVautherin** [comment]
> But when I press the take-off button, the app will crash.

I guess it throws an exception. What does it say?

**Comment by Zxr1230** [comment]
> > But when I press the take-off button, the app will crash.
> 
> I guess it throws an exception. What does it say?

Sorry for the late reply. I was working on something else. It doesn't throw any exception. The app just crashed and quit. Thank you!
![image](https://github.com/mavlink/MAVSDK-Java/assets/47097582/42e845e1-a175-4a38-8ddf-2bacffd35b05)

**Comment by JonasVautherin** [comment]
Well the app probably crashes by throwing an exception, but you won't see that in the Android popup :blush:. Did you check logcat?

**Comment by Zxr1230** [comment]
> Well the app probably crashes by throwing an exception, but you won't see that in the Android popup 😊. Did you check logcat?

Thank you! It said the command was denied. It means the drone denied the command right?
![image](https://github.com/mavlink/MAVSDK-Java/assets/47097582/527b22cd-f2d2-4d71-a2dd-e6191a70dcf7)
![image](https://github.com/mavlink/MAVSDK-Java/assets/47097582/5e7e9988-be98-4524-80f3-79bc8b9abab0)

**Comment by JonasVautherin** [comment]
> It means the drone denied the command right?

Yes!

**Comment by Zxr1230** [comment]
> > It means the drone denied the command right?
> 
> Yes!

Thank you! What could be the issue that makes flight mode doesn't work? Can this app control the drone to fly directly? For example fly it higher or lower, forward or backward.

**Comment by mfran89** [comment]
I would also like to jump on this thread, I currently am also having issues accessing the flight mode via 
```
_disposables.add(drone.getTelemetry().getFlightMode().subscribe(flightMode
                -> {
            Log.d(TAG,"flight mode:" + flightMode.name() + "flight mode number " + flightMode.ordinal());
        }));
```

I am able to get position telemetry and other variables but for some reason flight mode returns 0. Where as on mission planner I see the right flight mode. I am currently using Ardupilot and mavsdk 1.3.1 and mavsdk server 1.3.2.

**Comment by JonasVautherin** [comment]
> I am currently using Ardupilot and mavsdk 1.3.1 and mavsdk server 1.3.2.

I don't remember exactly, but some Ardupilot features were added for MAVSDK v2. Flight mode may be one?
