### ISSUE TITLE
Update MavSDK to 2.1.0

### ISSUE THREAD

**Issue by tkocik92** [mavlink/MAVSDK-Java#146]
Is it possible to update `MAVSDK-Java` to use `MavSDK 2.1.0`?

**Comment by JonasVautherin** [comment]
Good point, let me see that ASAP.

**Comment by JonasVautherin** [comment]
I just released mavsdk-java v2.0.0 to the maven repository. The packages should be there in a few hours. Would you mind trying them and letting me know if they work for you?

**Comment by JonasVautherin** [comment]
It is already there: https://central.sonatype.com/artifact/io.mavsdk/mavsdk

**Comment by tkocik92** [comment]
I confirmed the updates are available, but `implementation 'io.mavsdk:mavsdk:2.0.0'` appears to be missing its classes? `import io.mavsdk.System` and all related classes are throwing errors:
<img width="337" alt="Screenshot 2024-02-08 at 7 41 02 AM" src="https://github.com/mavlink/MAVSDK-Java/assets/7491879/ca4b2f95-3cb9-482b-a20f-7ba89063688e">

**Comment by JonasVautherin** [comment]
You're right, apparently with the newer version of gradle this got dropped in the publish task. I pushed again (io.mavsdk:mavsdk:2.0.1), would you mind trying that?

**Comment by tkocik92** [comment]
Everything is working again. Thanks!
