### ISSUE TITLE
How to adjust safety parameters (RTL on RC loss, Data Link Loss Trigger, etc) using the SDK APIs?

### ISSUE THREAD

**Issue by rayw-dronesense** [mavlink/MAVSDK-Java#152]
I can arm the aircraft, take off, and send RC manual controls and can adjust RTL altitude. But I can't seem to find a way to adjust the other safety settings...could you please help? Thanks!

The Android API appears to be based on https://github.com/mavlink/MAVSDK-Proto/tree/main/protos

**Comment by JonasVautherin** [comment]
Aren't those just params of the autopilot? If yes you can just use the params plugin of MAVSDK.

**Comment by julianoes** [comment]
Yes, it would be done using params.

The parameters are listed here: https://docs.px4.io/v1.14/en/advanced_config/parameter_reference.html#NAV_RCL_ACT
