### ISSUE TITLE
Excuse me, where can I find the API for MAVSDK-JAVA?

### ISSUE THREAD

**Issue by fuchenliang666** [mavlink/MAVSDK-Java#158]
Excuse me, where can I find the API for MAVSDK-JAVA?

**Comment by JonasVautherin** [comment]
It is auto-generated from https://github.com/mavlink/MAVSDK-Proto/tree/main/protos. It's always the same pattern, so if you look at the examples you should be able to infer the remaining functions, I would say :+1:.
