### ISSUE TITLE
How to use mavsdk_server_manylinux2010-x64?

### ISSUE THREAD

**Issue by wangpuxia** [mavlink/MAVSDK-Java#161]
I download mavsdk_server_manylinux2010-x64 file,but how to runing it?

**Comment by JonasVautherin** [comment]
Did you try `./mavsdk_server_manylinux2010-x64`?

**Comment by wangpuxia** [comment]
-bash: .: mavsdk_server_manylinux2010-x64: cannot execute binary file

**Comment by divyanshupundir** [comment]
Please try this:

```bash
chmod +x mavsdk_server_manylinux2010-x64
```

After this you should be able to run the binary as @JonasVautherin has explained earlier.

**Comment by julianoes** [comment]
@wangpuxia what machine is this on? Linux, macOS, x64, arm?

**Comment by wangpuxia** [comment]
> @wangpuxia what machine is this on? Linux, macOS, x64, arm?

CentOS Linux release 7.7

**Comment by wangpuxia** [comment]
> Please try this:
> 
> ```shell
> chmod +x mavsdk_server_manylinux2010-x64
> ```
> 
> After this you should be able to run the binary as @JonasVautherin has explained earlier

i tried,but error is same

**Comment by wangpuxia** [comment]
![image](https://github.com/mavlink/MAVSDK-Java/assets/125457380/8d3030e3-8f4c-4ae0-bd5e-03df3ab6d029)

**Comment by divyanshupundir** [comment]
There should be a `/` between the `.` and the binary name with no white space.

```bash
./mavsdk_server_manylinux2010-x64
```

**Comment by wangpuxia** [comment]
> There should be a `/` between the `.` and the binary name with no white space.
> 
> ```shell
> ./mavsdk_server_manylinux2010-x64
> ```

really help me ,thanks a lot

**Comment by wangpuxia** [comment]
![aa7a69d632e6e8c88d6d23788d8d29e](https://github.com/mavlink/MAVSDK-Java/assets/125457380/e9c91815-a1a5-4d8c-b77a-65a7e8286288)
runing mavlink-server succful on a server computer(with public IP), and open a port 18888

but at other computer,I cant connect this port 18888, telnet failed ,nmap failed
![image](https://github.com/mavlink/MAVSDK-Java/assets/125457380/66cc5e8e-36b4-483b-a36f-1ec5541b6420)

**Comment by julianoes** [comment]
You're trying nmap on TCP when it's probably UDP.

**Comment by julianoes** [comment]
Nevermind, it's TCP. In this case you need to look at your setup and firewall settings. It looks like your mavsdk_server is running in a virtual machine? Why are you running it in a virtual machine but then connecting outside in Windows?
