### ISSUE TITLE
Python-MAVSDK can't retrieve data from Mini Pix  after successful connection over serial USB 

### ISSUE THREAD

**Issue by rehadiri** [mavlink/MAVSDK-Java#45]
Hello,

I am trying telemetry.py example python code ( by modifying for serial connection ) to get telemetry data from my Mini Pix .  Mavsdk_server can connect to px4 , python code can connect mavsdk_server over tcp connection and i can see that drone discovered with UUID:1 message . But I cant get any data from flight controller.

When i switch to Mission Planer over the same USB connection Mission Planer can access any data in the px4, no problem at all. Very strange thing is that when i close MP and switch back to my python application my application also can get telemetry data without problem.

It seems that MP setting something in the Mini Pix but i dont know what is it ?

Is there a way to solve this problem ?

Thanks

**Comment by julianoes** [comment]
Sorry, it still sounds like you are using ArduPilot and not PX4. As said above, that's not supported at this time.
