### ISSUE TITLE
Update android example disposables

### ISSUE THREAD

**Issue by Katawann** [mavlink/MAVSDK-Java#57]
https://github.com/mavlink/MAVSDK-Java/blob/610ce377a3c03f5e0ead4d9cb1f36f9d526fff3c/examples/android-client/app/src/main/java/io/mavsdk/androidclient/MapsActivity.java#L112

Should we not clear the disposables with `disposables.clear()` after we dispose elements in `onPause()` ? As we add them again with `onResume()`

**Comment by JonasVautherin** [comment]
Good point! Would you mind opening a PR for that? :blush:

**Comment by Katawann** [comment]
#59

done !
