### ISSUE TITLE
Detecting serial connections with android.

### ISSUE THREAD

**Issue by MichaelSwan3** [mavlink/MAVSDK-Java#60]
Hi,

I am connecting via serial (to a px4) on android and you need to put in a serial connection string :

int mavsdkServerPort = mavsdkServer.run("serial:///bus/usb/001/003:1150200");
How can I:
* Tell what the connection string is - ie the bus/usb/001/003. I got bus/usb/001/003 from Q ground control.
* Detect when a new serial connection is successful.

When I plug in the serial device (PX4), q ground ground immediately wants to open it - how do I do that for my own application?

I've had a quick look through [https://github.com/mik3y/usb-serial-for-android](https://github.com/mik3y/usb-serial-for-android). Not sure if you are already using this or I need to implement it.

Is there a serial example for android?

I've a quick look at the q ground control source, not sure if I need to do this.

I assume all I need to do is: 
Get the connection strings
then should be able to drone.getAction().arm(); etc

Cheers
Michael Swan (emesent)

**Comment by JonasVautherin** [comment]
There has been work done in [this issue](https://github.com/mavlink/MAVSDK-Java/issues/23). I think there was good progress (getting a file descriptor from Android Java and passing it to `libmavsdk_server.so`, but for some reason it was not working.

It would be amazing if you could have a look at that and see if you manage to pass the file descriptor from Java to C++ over JNI successfully!

Let's continue the discussion there: https://github.com/mavlink/MAVSDK-Java/issues/23
