### ISSUE TITLE
`LogFiles#getDownloadLogFile` method doesn't work as expected

### ISSUE THREAD

**Issue by divyanshu1234** [mavlink/MAVSDK-Java#68]
This is the signature of the download log file method in log_files package in the Java version:
```
public Flowable<LogFiles.ProgressData> getDownloadLogFile()
```
And this is the corresponding one in Python:
```
async def download_log_file(self, entry, path):
```

The Java one doesn't have any parameters for entry and path and always throws `FILE_OPEN_FAILED: File Open Failed` error when I try to use it.

**Comment by julianoes** [comment]
Thanks for reporting @divyanshu1234. This looks indeed wrong, right @JonasVautherin?

**Comment by JonasVautherin** [comment]
Should be fixed in latest `main`. @divyanshu1234 could you give it a try? Then I could make a new release with those changes :+1:

**Comment by divyanshu1234** [comment]
I tried downloading a few logs using SITL and it is working fine. I will not be able to try it on hardware this week. But I've hardly ever faced any issue with MAVSDK that emerged using hardware that wasn't there in SITL.

Thanks for the fix.

**Comment by JonasVautherin** [comment]
Ok let's close it then, it will come in the next release (I'll try to create a release today or tomorrow)
