### ISSUE TITLE
Camera APIs with Gazebo Simulation not working

### ISSUE THREAD

**Issue by Saumya-NebCodes** [mavlink/MAVSDK-Java#82]
Hello Team,

I am trying to simulate a camera with Gazebo SITL. But the camera APIs seem to not working for me.

MAVSDK Java: 0.11
MAVSDK Server: 0.48.0
Gazebo command: `make px4_sitl_default gazebo_plane_cam`

Snippet:

`system.getCamera().getCaptureInfo()
                .subscribe( {
                    println("Picture taken: " + it.getFileUrl())
                }, {
                    println(it.toString())
                })`

None of the success or error subscriptions are called. If I use blockingFirst(), the code just hangs executing further. Same goes for other camera apis like `takePhoto()` etc. 

Please suggest.

**Comment by JonasVautherin** [comment]
Is `gazebo_plane_cam` supposed to support those commands? For instance, can you take pictures from QGC?
