### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by divyanshu1234** [mavlink/MAVSDK-Java#92]
@JonasVautherin can you please create a new release with the latest changes?

**Comment by divyanshu1234** [comment]
Sure.

**Comment by divyanshu1234** [comment]
Done https://github.com/mavlink/MAVSDK-Java/pull/93

**Comment by JonasVautherin** [comment]
Sorry something went wrong, please use 1.1.1 (just pushed it, will be on maven in a few hours)

**Comment by divyanshu1234** [comment]
Thanks a lot @JonasVautherin
