### ISSUE TITLE
getTelemetry().getRawGps is working but getTelemetry().getPosition isn't

### ISSUE THREAD

**Issue by jjcetraro** [mavlink/MAVSDK-Java#95]
I can connect to the drone with no problem, and I can get the position using the getRawGps method, but if I want to use getPosition instead, the callback is never executed. Why is that?

**Comment by JonasVautherin** [comment]
Are you sure that you have a GPS fix? Not sure what the raw gps gives you, but `getPosition` will only give you the position when there is a gps fix. So if you are e.g. indoors, it may just not have any.

**Comment by jjcetraro** [comment]
I think that was exactly the problem. Thanks for your soon reply!
